FROM nginx:alpine

RUN apk update && \
    apk add git && \ 
    apk add nodejs && \
    apk add npm

RUN git clone https://github.com/MasonUWF/SWM_P2.git

RUN mkdir -p /var/log/hotburger

WORKDIR /SWM_P2/Monitor

RUN npm i express -S

CMD ["node", "index.js"]