version: '3'

services:
	order:
		build:
			context: .
			dockerfile: ./order/Dockerfile
		ports:
			- "80:80"
		volumes:
			- /var/log/hotburger:/var/log/hotburger
	monitor:
		build:
			context: .
			dockerfile: ./monitor/Dockerfile
		ports:
			- "8080:8080"
		volumes:
			- /var/log/hotburger:/var/log/hotburger